apiVersion: v1
kind: Service
metadata:
  name: podium
  annotations:
    cloud.google.com/load-balancer-type: 'Internal'
    networking.gke.io/internal-load-balancer-allow-global-access: 'true'
  labels:
    app: podium
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: podium
  loadBalancerIP: 10.148.11.40