apiVersion: v1
kind: Service
metadata:
  name: podium
  labels:
    app: podium
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8880
      targetPort: 8880
    - name: grpc
      port: 8881
      targetPort: 8881
  selector:
    app: podium
