apiVersion: apps/v1
kind: Deployment
metadata:
  name: podium
spec:
  template:
    spec:
      containers:
      - name: podium
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            cpu: 150m
            memory: 512Mi
