apiVersion: apps/v1
kind: Deployment
metadata:
  name: podium
spec:
  template:
    spec:
      containers:
      - name: podium
        resources:
          requests:
            cpu: 50m
            memory: 128Mi
