name: podium dev

on:
  push:
    branches:
      - master
  workflow_dispatch:
    inputs:
      confirmDeployment:
        description: 'Confirm Deployment'
        required: true

env:
  PROJECT_ID: thetan-dev
  GKE_CLUSTER: thetan-dev-gke
  GKE_ZONE: asia-southeast1-c
  DEPLOYMENT_NAME: podium
  IMAGE: podium
  KUSTOMIZE_VERSION: 4.4.0

jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Grant execute permission for build.sh
      run: chmod +x custom_build.sh
    - name: Build
      run: ./custom_build.sh

    # Setup gcloud CLI
    - uses: google-github-actions/setup-gcloud@master
      with:
        version: '290.0.1'
        service_account_key: ${{ secrets.GKE_THETAN_DEV_SA_KEY }}
        project_id: ${{ env.PROJECT_ID }}

    - run: |-
        gcloud --quiet auth configure-docker

    - run: |-
        gcloud container clusters get-credentials "$GKE_CLUSTER" --zone "$GKE_ZONE"

    - name: Build
      run: |-
        docker build \
          --tag "gcr.io/$PROJECT_ID/$IMAGE:$GITHUB_SHA" \
          --build-arg GITHUB_SHA="$GITHUB_SHA" \
          --build-arg GITHUB_REF="$GITHUB_REF" \
          .
    # Push the Docker image to Google Container Registry
    - name: Publish
      run: |-
        docker push "gcr.io/$PROJECT_ID/$IMAGE:$GITHUB_SHA"

    - name: Set up Kustomize
      run: |-
        curl -SsLO https://github.com/kubernetes-sigs/kustomize/releases/download/kustomize/v${KUSTOMIZE_VERSION}/kustomize_v${KUSTOMIZE_VERSION}_linux_amd64.tar.gz
        tar -C /usr/local/bin/ -xf kustomize_v${KUSTOMIZE_VERSION}_linux_amd64.tar.gz

    # Deploy the Docker image to the GKE cluster
    - name: Deploy
      run: |-
        cd ./k8s/overlays/dev
        kustomize edit set image gcr.io/PROJECT_ID/IMAGE:TAG=gcr.io/$PROJECT_ID/$IMAGE:$GITHUB_SHA
        kustomize build . | kubectl apply -f -
        kubectl rollout status deployment/$DEPLOYMENT_NAME
        kubectl get services -o wide
