name: podium staging

on:
  workflow_dispatch: {}

env:
  gcpProjectID: thetan-staging
  arRepositoryName: thetan-arena
  imageName: podium
  workloadIdentityProvider: projects/911077854090/locations/global/workloadIdentityPools/github-actions/providers/github-oidc
  serviceAccount: github@thetan-staging.iam.gserviceaccount.com
  arUrl: asia-southeast1-docker.pkg.dev
  commitAuthorEmail: quan@wolffungame.com
  cfgRepoUrl: WolffunGame/thetan-arena-config
  cfgValuesFile: helm-values/staging/podium.yaml

jobs:
  build-push-update-tag:
    runs-on: ubuntu-20.04
    concurrency:
      group: thetan-arena-staging-${{ github.ref }}
      cancel-in-progress: true
    permissions:
      contents: "read"
      id-token: "write"
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          path: source

      - uses: cucxabong/github-actions/gloud-auth@main
        with:
          gcp_workload_identity_provider: ${{ env.workloadIdentityProvider }}
          gcp_service_account_email: ${{ env.serviceAccount }}

      - id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.arUrl }}/${{ env.gcpProjectID }}/${{ env.arRepositoryName }}/${{ env.imageName }}
          tags: |
            type=sha

      - uses: cucxabong/github-actions/build-push-update@main
        with:
          tags: ${{ steps.meta.outputs.tags }}
          context: ./source
          push: true
          cfgRepoUrl: ${{ env.cfgRepoUrl }}
          cfgValuesFile: ${{ env.cfgValuesFile }}
          commitAuthorEmail: ${{ env.commitAuthorEmail }}
          imageTagKey: ".image.tag"
          accessToken: ${{ secrets.IMAGE_TAG_UPDATE_WORKFLOW_GH_TOKEN }}
          codeRepository: ${{ github.repository }}
