name: podium production

on:
  workflow_dispatch:
    inputs:
      confirmDeployment:
        description: 'Confirm Deployment'
        required: true

env:
  PROJECT_ID: thetan-arena
  GKE_CLUSTER: thetan-production
  GKE_REGION: asia-southeast1
  WORKLOAD_IDENTITY_PROVIDER: projects/543249830504/locations/global/workloadIdentityPools/github-actions/providers/github-oidc
  SERVICE_ACCOUNT: githubaction@thetan-arena.iam.gserviceaccount.com
  DEPLOYMENT_NAME: podium
  IMAGE: podium
  KUSTOMIZE_VERSION: 4.4.0

jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Grant execute permission for build.sh
      run: chmod +x custom_build.sh
    - name: Build
      run: ./custom_build.sh

    - id: 'auth'
      name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v0'
      with:
        workload_identity_provider: ${{ env.WORKLOAD_IDENTITY_PROVIDER }}
        service_account: ${{ env.SERVICE_ACCOUNT }}

    - uses: google-github-actions/setup-gcloud@v0

    - run: |-
        gcloud --quiet auth configure-docker

    - run: |-
        gcloud container clusters get-credentials "$GKE_CLUSTER" --region "$GKE_REGION"

    - name: Build
      run: |-
        docker build \
          --tag "gcr.io/$PROJECT_ID/$IMAGE:$GITHUB_SHA" \
          --build-arg GITHUB_SHA="$GITHUB_SHA" \
          --build-arg GITHUB_REF="$GITHUB_REF" \
          .

    - name: Publish
      run: |-
        docker push "gcr.io/$PROJECT_ID/$IMAGE:$GITHUB_SHA"

    - name: Set up Kustomize
      run: |-
        curl -SsLO https://github.com/kubernetes-sigs/kustomize/releases/download/kustomize/v${KUSTOMIZE_VERSION}/kustomize_v${KUSTOMIZE_VERSION}_linux_amd64.tar.gz
        tar -C /usr/local/bin/ -xf kustomize_v${KUSTOMIZE_VERSION}_linux_amd64.tar.gz

    - name: Deploy
      run: |-
        cd ./k8s/overlays/production
        kustomize edit set image gcr.io/PROJECT_ID/IMAGE:TAG=gcr.io/$PROJECT_ID/$IMAGE:$GITHUB_SHA
        kustomize build . | kubectl apply -f -
        kubectl rollout status deployment/$DEPLOYMENT_NAME
