name: podium uat

on:
  workflow_dispatch:
    inputs:
      confirmDeployment:
        description: 'Confirm Deployment'
        required: true

env:
  PROJECT_ID: thetan-uat
  GKE_CLUSTER: thetan-uat
  GKE_REGION: asia-southeast1
  DEPLOYMENT_NAME: podium
  IMAGE: podium

jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Grant execute permission for build.sh
      run: chmod +x custom_build.sh
    - name: Build
      run: ./custom_build.sh

    # Setup gcloud CLI
    - uses: google-github-actions/setup-gcloud@v0
      with:
        version: '290.0.1'
        service_account_key: ${{ secrets.GKE_SA_KEY_UAT }}
        project_id: ${{ env.PROJECT_ID }}

    # Configure Docker to use the gcloud command-line tool as a credential
    # helper for authentication
    - run: |-
        gcloud --quiet auth configure-docker
    # Get the GKE credentials so we can deploy to the cluster
    - run: |-
        gcloud container clusters get-credentials "$GKE_CLUSTER" --region "$GKE_REGION"
    # Build the Docker image
    # - name: Generate ccy.json configuration file setting
    #   run: cp ccy.json.bk ./src/ccy.json

    - name: Build
      run: |-
        docker build \
          --tag "gcr.io/$PROJECT_ID/$IMAGE:$GITHUB_SHA" \
          --build-arg GITHUB_SHA="$GITHUB_SHA" \
          --build-arg GITHUB_REF="$GITHUB_REF" \
          .
    # Push the Docker image to Google Container Registry
    - name: Publish
      run: |-
        docker push "gcr.io/$PROJECT_ID/$IMAGE:$GITHUB_SHA"
    # Set up kustomize
    - name: Set up Kustomize
      run: |-
        curl -sfLo kustomize https://github.com/kubernetes-sigs/kustomize/releases/download/v3.1.0/kustomize_3.1.0_linux_amd64
        chmod u+x ./kustomize
    # Deploy the Docker image to the GKE cluster
    - name: Deploy
      run: |-
        cd ./k8s/overlays/uat
        ../../../kustomize edit set image gcr.io/PROJECT_ID/IMAGE:TAG=gcr.io/$PROJECT_ID/$IMAGE:$GITHUB_SHA
        ../../../kustomize build . | kubectl apply -f -
