name: thetan-rival Open Beta

on:
  workflow_dispatch: {}
  push:
    branches:
      - master

jobs:
  build-and-push:
    permissions:
      contents: "read"
      id-token: "write"
    uses: ./.github/workflows/build-image.yaml
    with:
      project_id: thetan-rival
      service_account_email: github-actions@thetan-rival.iam.gserviceaccount.com
      workload_identity_provider: projects/417983751839/locations/global/workloadIdentityPools/github-actions/providers/github-oidc
      image_name: podium
  update-image-tag:
    needs:
      - build-and-push
    uses: ./.github/workflows/update-image-tag.yaml
    with:
      config_repo_url: WolffunGame/thetan-rival-config
      config_values_file: charts/wolffun-service/helm-values/open-beta/podium.yaml
      image_tag_key: ".image.tag"
      image_tag: ${{ github.sha }}
      project_id: thetan-rival
    secrets:
      access_token: ${{ secrets.IMAGE_TAG_UPDATE_WORKFLOW_GH_TOKEN }}
