name: Update image tag

on:
  workflow_call:
    secrets:
      access_token:
        required: true
    inputs:
      config_repo_url:
        type: string
        required: true
      config_values_file:
        type: string
        required: true
      image_tag_key:
        type: string
        required: true
      image_tag:
        type: string
        required: true
      image_name:
        type: string
        required: true
      project_id:
        required: true
        type: string
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: "read"
      id-token: "write"
    steps:
      - name: Checkout config repo
        uses: actions/checkout@v3
        with:
          repository: ${{ inputs.config_repo_url }}
          token: ${{ secrets.access_token }}
          ref: main
          path: config-repo
      - name: update new tag
        run: |
          yq -ei "${{ inputs.image_tag_key }} |= strenv(IMAGE_TAG)" "${{ inputs.config_values_file }}"
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "Update '${{ inputs.project_id }}' ${{ inputs.image_name }} image tag to ${IMAGE_TAG}"
          git push origin main
        env:
          IMAGE_TAG: ${{ inputs.image_tag }}
        working-directory: config-repo
